//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMXDBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicacao
    {
        public string AplicacaoId { get; set; }
        public string Nome { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public string IdUsuarioInicio { get; set; }
        public string IdUsuarioFim { get; set; }
        public string PagSeguroToken { get; set; }
        public string LayoutChoose { get; set; }
        public Nullable<int> Posicao { get; set; }
        public string mailUser { get; set; }
        public string mailPassword { get; set; }
        public string mailServer { get; set; }
        public Nullable<int> mailPort { get; set; }
        public Nullable<byte> isSecure { get; set; }
        public string pageFacebook { get; set; }
        public string pageLinkedin { get; set; }
        public string pageInstagram { get; set; }
        public string pageTwitter { get; set; }
        public string pagePinterest { get; set; }
        public string pageFlicker { get; set; }
        public byte[] logotipo { get; set; }
        public string googleAdSense { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string header { get; set; }
    }
}
