//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMXDBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class arquivo
    {
        public string ArquivoId { get; set; }
        public string AreaId { get; set; }
        public string ConteudoId { get; set; }
        public string Nome { get; set; }
        public string TipoId { get; set; }
    }
}
