//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagem
    {
        public string ImagemId { get; set; }
        public string Url { get; set; }
        public Nullable<int> Largura { get; set; }
        public Nullable<int> Altura { get; set; }
        public string AreaId { get; set; }
        public string ConteudoId { get; set; }
        public string Descricao { get; set; }
        public string ParentId { get; set; }
        public string TipoId { get; set; }
    }
}
