//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string UserId { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Apelido { get; set; }
        public string Senha { get; set; }
        public Nullable<byte> Ativo { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
    }
}
