//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciaaerea
    {
        public string CiaAereaId { get; set; }
        public string Descricao { get; set; }
        public string Logotipo { get; set; }
        public string Descricao_Longa { get; set; }
        public Nullable<byte> Ativo { get; set; }
        public Nullable<byte> TipoNac { get; set; }
        public Nullable<byte> TipoInt { get; set; }
        public string webticket_str { get; set; }
    }
}
