//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class conteudo
    {
        public string ConteudoId { get; set; }
        public string AreaId { get; set; }
        public string Autor { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public string CategoriaId { get; set; }
    }
}
