//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class formularionew
    {
        public int IdForm { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Texto { get; set; }
        public Nullable<int> Ativo { get; set; }
    }
}
