//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class infofoto
    {
        public string FotoId { get; set; }
        public string FotoUrl { get; set; }
        public string Descricao { get; set; }
        public string CategoriaId { get; set; }
    }
}
