//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class informativo
    {
        public string InfoId { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Texto { get; set; }
        public string Foto { get; set; }
        public Nullable<byte> Ativo { get; set; }
        public string TipoEnvio { get; set; }
    }
}
