//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcao
    {
        public string OpcaoId { get; set; }
        public System.Guid AtributoId { get; set; }
        public int Qtd { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Estoque { get; set; }
    }
}
