//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public string ProdutoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Destaque { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public string CategoriaId { get; set; }
        public string AplicacaoId { get; set; }
        public string sku { get; set; }
        public string PagSeguroKey { get; set; }
        public string DetalheTecnico { get; set; }
        public string DescricaCurta { get; set; }
        public string produtocol { get; set; }
    }
}
