//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class refatributoxopcao
    {
        public System.Guid relacaoid { get; set; }
        public System.Guid atributoid { get; set; }
        public System.Guid opcaoid { get; set; }
    }
}
