//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialmedia
    {
        public string SocialMediaId { get; set; }
        public string AplicacaoId { get; set; }
        public Nullable<int> SocialMediaTypeId { get; set; }
        public string SocialMediaLink { get; set; }
    }
}
