//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class areas
    {
        public string AreaId { get; set; }
        public string AplicacaoId { get; set; }
        public string Nome { get; set; }
        public string Url { get; set; }
        public string Descricao { get; set; }
        public string AreaIdPai { get; set; }
        public Nullable<System.DateTime> DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public Nullable<byte> Imagem { get; set; }
        public Nullable<byte> MenuLateral { get; set; }
        public Nullable<byte> MenuSplash { get; set; }
        public Nullable<byte> MenuCentral { get; set; }
        public Nullable<int> posicao { get; set; }
        public Nullable<byte> MenuFixo { get; set; }
        public Nullable<byte> ListaSimples { get; set; }
        public Nullable<byte> ListaSplash { get; set; }
        public Nullable<byte> ListaBanner { get; set; }
        public Nullable<int> TipoArea { get; set; }
    }
}
