//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario
    {
        public string formularioid { get; set; }
        public string nome { get; set; }
        public string valor { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<System.DateTime> datainclusao { get; set; }
        public string areaid { get; set; }
    }
}
