//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class relatributoxproduto
    {
        public System.Guid Relacaoid { get; set; }
        public System.Guid Atributoid { get; set; }
        public System.Guid ProdutoId { get; set; }
    }
}
