//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class relmoduloconfaplicacao
    {
        public string RelacaoId { get; set; }
        public string ModuloConfId { get; set; }
        public string AplicacaoId { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public System.DateTime DataFinalizacao { get; set; }
    }
}
