//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSXDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoenvio
    {
        public string TipoEnvioId { get; set; }
        public string TipoEnvioDesc { get; set; }
    }
}
